create database IfBooks;
use IfBooks;

-- Tabela User
CREATE TABLE USUARIO (
    BD_EMAIL VARCHAR(150) PRIMARY KEY,
    BD_NOMECOMPLETO VARCHAR(200) NOT NULL,
    BD_NASCIMENTO DATE NOT NULL,
    BD_CELULAR VARCHAR(14) NOT NULL,
    BD_SENHA VARCHAR(100) NOT NULL,
    BD_CEP VARCHAR(9) NOT NULL,
    BD_ENDERECO VARCHAR(300) NOT NULL,
    BD_NUMERO VARCHAR(20) NOT NULL,
    BD_COMPLEMENTO VARCHAR(120) NOT NULL,
    BD_BAIRRO VARCHAR(200) NOT NULL,
    BD_CIDADE VARCHAR(200) NOT NULL,
    BD_UF VARCHAR(100) NOT NULL
);

-- Tabela Livros
CREATE TABLE LIVROS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    BD_NOME VARCHAR(100) NOT NULL,
    BD_CAPA VARBINARY(8000) NOT NULL,
    BD_EDITORA VARCHAR(100) NOT NULL,
    BD_ANOLANCAMENTO INT NOT NULL,
    BD_AUTORA VARCHAR(100) NOT NULL,
    BD_TROCA BOOLEAN NOT NULL,
    BD_DOACAO BOOLEAN NOT NULL,
    BD_MATERIA VARCHAR(100) NOT NULL,
    BD_EMAIL_USUARIO VARCHAR(150) NOT NULL,
    FOREIGN KEY (BD_EMAIL_USUARIO) REFERENCES USUARIO(BD_EMAIL)
);

dsadada